deployment:
  tasks:
    - export DEPLOYPATH=/home/arslogis/tracking.arslogistic.id
    - set -e
    - /bin/cp -R * $DEPLOYPATH
    - cd $DEPLOYPATH
    - /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader
    - chmod -R 775 storage bootstrap/cache
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
